<?php 
$I = new AcceptanceTester($scenario);
$I->wantTo('Create users with different roles');
$I->amOnPage('/');
$I->click('Sign in');
$I->dontsee('Enter your Devtrac Test The Tests username.');
$I->see('Enter your Devtrac Test username');
$I->see('Enter the password that accompanies your username.');
$I->fillField('name','admin');
$I->fillField('pass','admin');
$I->click('Log in');
$I->dontsee('Sorry, unrecognized username or password');
$I->dontseeLink('Have you forgotten your password?');
$I->see('Welcome, admin');
$I->amGoingTo('submit user edit form/page');
$I->click('Edit My Profile');
$I->fillField('name','admin');
$I->selectOption('taxonomy_vocabulary_5[und]','Supervisor');
$I->fillField('field_user_superior[und][0][target_id]','admin');
$I->selectOption('taxonomy_vocabulary_4[und]','Education');
$I->fillField('field_user_firstname[und][0][value]','admin');
$I->fillField('field_user_surname[und][0][value]','admin');
$I->fillField('field_user_aboutme[und][0][value]',' am here to test please dont worry am just a dummy admin');
$I->click('Save');